import pyautogui import time


#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED
# Presses the space key
pyautogui.press("space")
#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHE
# Presses the w key once
pyautogui.press("w")

# Presses the enter key once#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHED#PATCHE
pyautogui.press("enter")

# Ends it from going too fast, if you want to risk dying in game, change time.sleep's time.
time.sleep (0.5)

# Presses enter one last time.
pyautogui.press("enter")

end
end
#update
